// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Detail: typeof import('./src/components/Detail.vue')['default']
    Echart: typeof import('./src/components/lib/Echart.vue')['default']
    EChart: typeof import('./src/components/lib/EChart.vue')['default']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Home: typeof import('./src/components/Home.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    RecordCalc: typeof import('./src/components/RecordCalc.vue')['default']
    RecordIcon: typeof import('./src/components/RecordIcon.vue')['default']
    RecordNode: typeof import('./src/components/RecordNode.vue')['default']
    RecordTime: typeof import('./src/components/RecordTime.vue')['default']
    RecordType: typeof import('./src/components/RecordType.vue')['default']
    Statistic: typeof import('./src/components/Statistic.vue')['default']
    Tab: typeof import('./src/components/lib/Tab.vue')['default']
    Tabs: typeof import('./src/components/lib/Tabs.vue')['default']
  }
}

export { }
